spring:
  data:
    mongodb:
      uri: mongodb://localhost:30002/mongod

  shell:
    interactive:
      enabled: true
  #    main:
  #      allow-circular-references: true

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.fedbon.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    root: ERROR
