spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd

  sql:
    init:
      #      mode: never
      mode: always
  #      data-locations: data.sql
  #      schema-locations: schema.sql

  jmx:
    enabled: true

  jpa:
    generate-ddl: false
    open-in-view: false

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "metrics,health,logfile,prometheus"
  endpoint:
    metrics:
      enabled: true
    health:
      enabled: true
      show-components: always
      show-details: when-authorized
      roles: "ADMIN"
    logfile:
      enabled: true
    prometheus:
      enabled: true

logging:
  level:
    root: INFO
  file:
    name: "hw17/logs/application.log"
  pattern:
    file: "%d %p [%t] [%c:%L] %m%n"